export const iconMap = {
  W: "ms-w ms-ci-w",
  U: "ms-u ms-ci-u",
  B: "ms-b ms-ci-b",
  R: "ms-r ms-ci-r",
  G: "ms-g ms-ci-g",
  1: "ms-1",
  2: "ms-2",
  3: "ms-3",
  4: "ms-4",
  5: "ms-5",
  6: "ms-6",
  7: "ms-7",
  8: "ms-8",
  9: "ms-9",
  10: "ms-10",
  11: "ms-11",
  12: "ms-12",
  13: "ms-13",
  14: "ms-14",
  15: "ms-15",
  16: "ms-16",
  17: "ms-17",
  18: "ms-18",
  19: "ms-19",
  20: "ms-20",
  "W/U": "ms-wu ms-ci-wu",
  "W/B": "ms-wb ms-ci-wb",
  "U/B": "ms-ub ms-ci-ub",
  "U/R": "ms-ur ms-ci-ur",
  "B/R": "ms-br ms-ci-br",
  "B/G": "ms-bg ms-ci-bg",
  "R/G": "ms-rg ms-ci-rg",
  "R/W": "ms-rw ms-ci-rw",
  "G/W": "ms-gw ms-ci-gw",
  "G/U": "ms-gu ms-ci-gu",
  "2/W": "ms-2w ms-ci-2w",
  "2/U": "ms-2u ms-ci-2u",
  "2/B": "ms-2b ms-ci-2b",
  "2/R": "ms-2r ms-ci-2r",
  "2/G": "ms-2g ms-ci-2g",
  "W/P": "ms-wp ms-ci-w",
  "U/P": "ms-up ms-ci-u",
  "B/P": "ms-bp ms-ci-b",
  "R/P": "ms-rp ms-ci-r",
  "G/P": "ms-gp ms-ci-g",
  "G/U/P": "ms-p ms-split ms-pp ms-ci-gu",
};
